version: '3'

services:

  postgres:
    image: "postgres:11.9-alpine"
    ports:
      - "5400:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev
    volumes:
      - "./initial-data.sql:/docker-entrypoint-initdb.d/initial-data.sql"

